version: '3'
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=simpli-coding-challenge
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - mongodb
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
