version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile    
    ports:
      - '4000:4000'
    environment:
      PORT: 4000
      MONGO_URI: 'mongodb+srv://mongo:mongo@simplicoding.4u97duj.mongodb.net/?retryWrites=true&w=majority'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:4000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      BACKEND_URL: 'http://backend:4000'
    depends_on:
      backend:
        condition: service_healthy 

    
