import Head from 'next/head';
import Button from '../components/Button';
import Link from '@/components/Link';
import Title from '@/components/Title';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Title level={1}>Welcome to my coding challenge</Title>
        <p>
          This is my coding challenge where I demonstrate my Next.js skills.
          Feel free to explore the app and its features!
        </p>
        <div>
          <Link href='/products'>
            <Button variant='primary'>Products</Button>
          </Link>
          <Link href='/management'>
            <Button variant='primary'>Management</Button>
          </Link>
        </div>
        <p>
          In the <b>Products</b> section, you can see the full list of products.
          In the <b>Management</b> section, you can add, edit, or delete
          products.
        </p>
      </main>
    </>
  );
}
